<?php
$terms = array(
  285 => 'Other',
  120 => 'Accounting Software',
  143 => 'Business Application',
  153 => 'Change Management',
  159 => 'Commercial Software',
  163 => 'Contact Management Software',
  166 => 'Customer Information Control System (CICS)',
  167 => 'Customer Relationship Management (CRM)',
  169 => 'Data Management Solution',
  213 => 'Enterprise Resource Planning',
  144 => 'Business Integration',
  145 => 'Business Intelligence',
  252 => 'Job Management',
  277 => 'Office Suite',
  294 => 'Permormance Management',
  304 => 'Presentation Software',
  146 => 'Business Process Management (BPM)',
  301 => 'PLM (Product Lifecycle Management)',
  313 => 'Project Management Software',
  334 => 'Spreadsheet',
  173 => 'Database',
  174 => 'Database Administrator',
  237 => 'IDMS (Integrated Database Management System)',
  175 => 'Database Management Software',
  180 => 'Database Management Systems - Utilities',
  176 => 'Database Management System-(Object-Relational)',
  181 => 'Database Programming Language',
  179 => 'Database Management Systems - Ralational',
  139 => 'Backup Software',
  170 => 'Data Recovery Software',
  187 => 'Diagnostic Software',
  194 => 'Disk Cloning',
  195 => 'Disk Partitioning',
  196 => 'Distributed File System',
  218 => 'File Server',
  260 => 'Maintenance & Optimization',
  308 => 'Profiler / Memory Debugger',
  265 => 'Middleware Management',
  268 => 'Monitoring Software',
  274 => 'Network Management Software',
  331 => 'Software Configuration Management (SCM)',
  332 => 'Software Installation Tools',
  340 => 'Systems Management',
  341 => 'Tape Management',
  352 => 'Uninstallers',
  353 => 'Utility Program',
  361 => 'Virtual Machine',
  370 => 'Web Server',
  154 => 'Charting Software',
  184 => 'Desktop Publishing',
  188 => 'Diagramming Software',
  293 => 'PDF Software',
  199 => 'Document Processing',
  326 => 'Screenwriting Software',
  348 => 'Text Editing Software',
  377 => 'Word Processor',
  134 => 'Audio Drivers',
  141 => 'Bluetooth Software',
  150 => 'Camera Drivers',
  152 => 'CD Burners',
  204 => 'DVD Software',
  254 => 'Keyboard Drivers',
  257 => 'Mainframe',
  269 => 'Motherboard Drivers',
  273 => 'Network Drivers',
  305 => 'Printer Software',
  357 => 'Video Drivers',
  373 => 'Webcam Software',
  208 => 'Educational Software',
  255 => 'Language Software',
  262 => 'Math Software',
  323 => 'Science Software',
  342 => 'Teaching Tools',
  124 => 'Alarms & Clock Software',
  142 => 'Brainstorming And Mind-Mapping Software',
  149 => 'Calendar & Time Management Software',
  168 => 'Data Compression',
  215 => 'File Compression',
  216 => 'File Management',
  297 => 'Personal Information Manager',
  322 => 'Schedule Management',
  165 => 'Cursors',
  183 => 'Desktop Customization',
  235 => 'Icon Tools',
  256 => 'Launchers',
  290 => 'Parental Control',
  325 => 'Screensavers',
  226 => 'Game',
  121 => 'Action Games',
  123 => 'Adventure Games',
  131 => 'Arcade Games',
  151 => 'Cards & Lottery',
  202 => 'Driving Games',
  221 => 'First-Person Shooters',
  300 => 'Platformer Games',
  316 => 'Real-Time Strategy Games',
  321 => 'Role-Playing',
  333 => 'Sports Games',
  337 => 'Strategy Games',
  227 => 'Games Utilities & Editors',
  230 => 'Graphics Software',
  116 => '3D Computer Graphics',
  117 => '3D Modeling Software',
  125 => 'Animation Software',
  162 => 'Computer-Aided Design (CAD)',
  222 => 'Flash Software',
  229 => 'Geographic Information System (GIS)',
  299 => 'Photography Software',
  315 => 'Raster Graphics Editor',
  354 => 'Vector Graphics Editor',
  363 => 'Wallpaper Editors & Tools',
  367 => 'Web Designing',
  190 => 'Digital Audio And MIDI Software',
  135 => 'Audio Player',
  136 => 'Audio Plugins',
  137 => 'Audio Production & Recording Software',
  197 => 'DJ Software',
  263 => 'Media Management',
  238 => 'Illustration Software',
  251 => 'IPod Utilities',
  270 => 'Multimedia Framework',
  271 => 'Music Management Software',
  338 => 'Streaming Audio Software',
  284 => 'Optical Disc Authoring',
  239 => 'Image Editing Software',
  240 => 'Image Organizer',
  298 => 'Photo Sharing & Publishing',
  264 => 'Media Player',
  320 => 'Rippers & Converting Software',
  355 => 'Video Capture Software',
  356 => 'Video Converters',
  358 => 'Video Editing Software',
  359 => 'Video Players',
  138 => 'Automation Software',
  140 => 'Barcode Software',
  186 => 'Device Specific Subsystems',
  201 => 'DreamQuest',
  207 => 'EBooks',
  212 => 'Engineering Software',
  231 => 'Grid Computing',
  232 => 'Handheld Electronic Devices',
  233 => 'Hobby Software',
  288 => 'Output Management',
  302 => 'Portable Applications',
  350 => 'Themes',
  364 => 'Weather Software',
  374 => 'Widget Toolkit',
  225 => 'Gadgets & Widgets',
  282 => 'Operating System',
  128 => 'Application Development',
  160 => 'Compiler',
  234 => 'HTML Editor',
  243 => 'Integrated Development Environment (IDE)',
  249 => 'Interpreters & Compilers',
  310 => 'Programming Language',
  314 => 'Rapid Application Development',
  312 => 'Programming Languages - Utilities',
  368 => 'Web Development Software',
  378 => 'XML Tools',
  132 => 'Astrology Software',
  318 => 'Religious Software',
  126 => 'Antivirus',
  211 => 'Encryption Software',
  220 => 'Firewall Software',
  248 => 'Internet Security Software Suites',
  291 => 'Password Manager',
  306 => 'Privacy Software',
  336 => 'Spyware Remover',
  343 => 'Telecommunications',
  155 => 'Chat',
  172 => 'Data Transfer & Sync Software',
  189 => 'Dial-up Software',
  206 => 'E-mail Software',
  224 => 'FTP Software',
  242 => 'Instant Messaging Client',
  246 => 'Internet related',
  247 => 'Internet Relay Chat (IRC) Client',
  276 => 'Networking Software',
  289 => 'P2P & File-Sharing Software',
  319 => 'Remote Access',
  329 => 'SMS Tools',
  360 => 'VideoConferencing',
  369 => 'Web Phones & VoIP Software',
  375 => 'Wireless Networking Software',
  122 => 'ActiveX',
  156 => 'Chrome Extensions',
  219 => 'Firefox Add-ons & Plugins',
  244 => 'Internet Explorer Add-ons & Plugins',
  286 => 'Other Browser Add-ons & Plugins',
  372 => 'Web-based Aggregator',
  365 => 'Web Analytics',
  366 => 'Web Browsers',
  164 => 'Content Management System (CMS)',
  200 => 'Download Managers',
  205 => 'E-Business Suite',
  279 => 'Online Form Tools',
  280 => 'Online Service',
  281 => 'Online Storage & Data Backup',
  327 => 'Search Tools',
  328 => 'SEO Tools',
  371 => 'Web Site Tools',
  330 => 'Social Networking Software',
);

$new_name_terms = array('-OTHER-',
	'Business - Accounting',
	'Business - Application',
	'Business - Change Management',
	'Business - Commercial',
	'Business - Contact Management',
	'Business - Customer Info Cntl Sys (CICS)',
	'Business - Customer Rel Mgt (CRM)',
	'Business - Data Management',
	'Business - Enterprise Res Planning (ERP)',
	'Business - Integration',
	'Business - Intelligence',
	'Business - Job Management',
	'Business - Office Suite',
	'Business - Performance Management',
	'Business - Presentations',
	'Business - Process Management (BPM)',
	'Business - Product Lifecycle Mgt (PLM)',
	'Business - Project Management',
	'Business - Spreadsheets',
	'Database',
	'Database - Administration',
	'Database - Integrated (IDBMS)',
	'Database - Management',
	'Database - Management - Utilities',
	'Database - Object Relational',
	'Database - Programming Language',
	'Database - Relational',
	'DevOps - Backup',
	'DevOps - Data Recovery Software',
	'DevOps - Diagnostics',
	'DevOps - Disk Cloning',
	'DevOps - Disk Partitioning',
	'DevOps - Distributed File System',
	'DevOps - File Server',
	'DevOps - Maintenance & Optimization',
	'DevOps - Memory Debugger',
	'DevOps - Middleware Management',
	'DevOps - Monitoring',
	'DevOps - Network Management',
	'DevOps - Software Config Mgt (SCM)',
	'DevOps - Software Installation',
	'DevOps - Systems Management',
	'DevOps - Tape Management',
	'DevOps - Uninstaller',
	'DevOps - Utility',
	'DevOps - Virtual Machine',
	'DevOps - WebServer',
	'Documents - Charting',
	'Documents - Desktop Publishing',
	'Documents - Diagramming',
	'Documents - PDF',
	'Documents - Processing',
	'Documents - Screenwriting',
	'Documents - Text Editing',
	'Documents - Word Processing',
	'Driver - Audio',
	'Driver - Bluetooth',
	'Driver - Camera',
	'Driver - CD Burner',
	'Driver - DVD Software',
	'Driver - Keyboard',
	'Driver - Mainframe',
	'Driver - Motherboard',
	'Driver - Network',
	'Driver - Printer',
	'Driver - Video',
	'Driver - Webcam',
	'Educational',
	'Educational - Language',
	'Educational - Math',
	'Educational - Science',
	'Educational - Teaching',
	'Efficiency - Alarms & Clocks',
	'Efficiency - Brainstorming',
	'Efficiency - Calendar & Time Mgt',
	'Efficiency - Data Compression',
	'Efficiency - File Compression',
	'Efficiency - File Management',
	'Efficiency - Personal Info Mgr (PIM)',
	'Efficiency - Schedule Management',
	'Utility - Cursors',
	'Utility - Desktop Customization',
	'Utility - Icon Tools',
	'Utility - Launchers',
	'Utility - Parental Controls',
	'Utility - Screensavers',
	'Games - - Uncategorized',
	'Games - Action Games',
	'Games - Adventure',
	'Games - Arcade',
	'Games - Cards & Lottery',
	'Games - Driving',
	'Games - First Person Shooters',
	'Games - Platformer',
	'Games - RealTime Strategy',
	'Games - RolePlaying Games',
	'Games - Sports',
	'Games - Strategy',
	'Games - Utilities & Editors',
	'Graphics - - Uncategorized',
	'Graphics - 3D',
	'Graphics - 3D Modeling',
	'Graphics - Animation',
	'Graphics - Comp Aided Design (CAD)',
	'Graphics - Flash',
	'Graphics - Geographic Info Sys (GIS)',
	'Graphics - Photography',
	'Graphics - Raster Editor',
	'Graphics - Vector Editor',
	'Graphics - Wallpaper Editors & Tools',
	'Graphics - Web Design',
	'Media - Audio - MIDI',
	'Media - Audio Player',
	'Media - Audio Plugin',
	'Media - Audio Production',
	'Media - DJ',
	'Media - File Management',
	'Media - Illustration',
	'Media - iPod Utilities',
	'Media - Multimedia Framework',
	'Media - Music Management',
	'Media - Music Streaming',
	'Media - Optical Disc Authoring',
	'Media - Photo Editing',
	'Media - Photo Organization',
	'Media - Photo Sharing & Publishing',
	'Media - Player',
	'Media - Rippers & Converters',
	'Media - Video Capture',
	'Media - Video Converters',
	'Media - Video Editor',
	'Media - Video Player',
	'Misc - Automation',
	'Misc - Barcode',
	'Misc - Device Specific Subsystems',
	'Misc - DreamQuest',
	'Misc - eBooks',
	'Misc - Engineering',
	'Misc - Grid Computing',
	'Misc - Handheld Electronic Devices',
	'Misc - Hobbies',
	'Misc - Output Management',
	'Misc - Portable',
	'Misc - Themes',
	'Misc - Weather',
	'Misc - Widget Toolkit',
	'Misc - Widgets',
	'Operating Systems',
	'Programming - App Dev Tool',
	'Programming - Compiler',
	'Programming - HTML Editor',
	'Programming - IDE',
	'Programming - Interpreter',
	'Programming - Language',
	'Programming - Rapid App Dev (RAD)',
	'Programming - Utilities',
	'Programming - Web Development',
	'Programming - XML',
	'Religion - Astrology',
	'Religion - Other',
	'Security - Antivirus',
	'Security - Encryption',
	'Security - Firewall',
	'Security - Internet',
	'Security - Passwords',
	'Security - Privacy',
	'Security - Spyware Remover',
	'Telcom - - Uncategorized',
	'Telcom - Chat',
	'Telcom - Data Transfer & Sync',
	'Telcom - Dialup',
	'Telcom - Email Client',
	'Telcom - FTP Software',
	'Telcom - Instant Messaging',
	'Telcom - Internet',
	'Telcom - IRC Client',
	'Telcom - Networking',
	'Telcom - P2P & File-Sharing',
	'Telcom - Remote Access',
	'Telcom - SMS',
	'Telcom - VideoConferencing',
	'Telcom - Web Phones & VoIP',
	'Telcom - Wireless',
	'Web - ActiveX',
	'Web - AddOns - Chrome',
	'Web - AddOns - Firefox',
	'Web - AddOns - IE',
	'Web - AddOns - Other',
	'Web - Aggregator',
	'Web - Analytics',
	'Web - Browser',
	'Web - Content Management (CMS)',
	'Web - Download Manager',
	'Web - eBusiness Suite',
	'Web - Online Form Tool',
	'Web - Online Service',
	'Web - Online Storage & Backup',
	'Web - Search Tool',
	'Web - SEO',
	'Web - Site Tool',
	'Web - Social Networking',
	);
$new_terms = array_combine($terms, $new_name_terms);

foreach ($new_terms as $old_name => $new_name) {
	$term = taxonomy_get_term_by_name($name, 'software_type');
	if(!empty($term)){
		$keys_terms[$term->tid] = $term->name;
	}
}
dpm($new_terms);
