<?php

$terms = array('Other',
	'Accounting Software',
	'Business Application',
	'Change Management',
	'Commercial Software',
	'Contact Management Software',
	'Customer Information Control System (CICS)',
	'Customer Relationship Management (CRM)',
	'Data Management Solution',
	'Enterprise Resource Planning',
	'Business Integration',
	'Business Intelligence',
	'Job Management',
	'Office Suite',
	'Permormance Management',
	'Presentation Software',
	'Business Process Management (BPM)',
	'PLM (Product Lifecycle Management)',
	'Project Management Software',
	'Spreadsheet',
	'Database',
	'Database Administrator',
	'IDMS (Integrated Database Management System)',
	'Database Management Software',
	'Database Management Systems - Utilities',
	'Database Management System-(Object-Relational)',
	'Database Programming Language',
	'Database Management Systems - Ralational',
	'Backup Software',
	'Data Recovery Software',
	'Diagnostic Software',
	'Disk Cloning',
	'Disk Partitioning',
	'Distributed File System',
	'File Server',
	'Maintenance & Optimization',
	'Profiler / Memory Debugger',
	'Middleware Management',
	'Monitoring Software',
	'Network Management Software',
	'Software Configuration Management (SCM)',
	'Software Installation Tools',
	'Systems Management',
	'Tape Management',
	'Uninstallers',
	'Utility Program',
	'Virtual Machine',
	'Web Server',
	'Charting Software',
	'Desktop Publishing',
	'Diagramming Software',
	'PDF Software',
	'Document Processing',
	'Screenwriting Software',
	'Text Editing Software',
	'Word Processor',
	'Audio Drivers',
	'Bluetooth Software',
	'Camera Drivers',
	'CD Burners',
	'DVD Software',
	'Keyboard Drivers',
	'Mainframe',
	'Motherboard Drivers',
	'Network Drivers',
	'Printer Software',
	'Video Drivers',
	'Webcam Software',
	'Educational Software',
	'Language Software',
	'Math Software',
	'Science Software',
	'Teaching Tools',
	'Alarms & Clock Software',
	'Brainstorming And Mind-Mapping Software',
	'Calendar & Time Management Software',
	'Data Compression',
	'File Compression',
	'File Management',
	'Personal Information Manager',
	'Schedule Management',
	'Cursors',
	'Desktop Customization',
	'Icon Tools',
	'Launchers',
	'Parental Control',
	'Screensavers',
	'Game',
	'Action Games',
	'Adventure Games',
	'Arcade Games',
	'Cards & Lottery',
	'Driving Games',
	'First-Person Shooters',
	'Platformer Games',
	'Real-Time Strategy Games',
	'Role-Playing',
	'Sports Games',
	'Strategy Games',
	'Games Utilities & Editors',
	'Graphics Software',
	'3D Computer Graphics',
	'3D Modeling Software',
	'Animation Software',
	'Computer-Aided Design (CAD)',
	'Flash Software',
	'Geographic Information System (GIS)',
	'Photography Software',
	'Raster Graphics Editor',
	'Vector Graphics Editor',
	'Wallpaper Editors & Tools',
	'Web Designing',
	'Digital Audio And MIDI Software',
	'Audio Player',
	'Audio Plugins',
	'Audio Production & Recording Software',
	'DJ Software',
	'Media Management',
	'Illustration Software',
	'IPod Utilities',
	'Multimedia Framework',
	'Music Management Software',
	'Streaming Audio Software',
	'Optical Disc Authoring',
	'Image Editing Software',
	'Image Organizer',
	'Photo Sharing & Publishing',
	'Media Player',
	'Rippers & Converting Software',
	'Video Capture Software',
	'Video Converters',
	'Video Editing Software',
	'Video Players',
	'Automation Software',
	'Barcode Software',
	'Device Specific Subsystems',
	'DreamQuest',
	'Ebooks',
	'Engineering Software',
	'Grid Computing',
	'Handheld Electronic Devices',
	'Hobby Software',
	'Output Management',
	'Portable Applications',
	'Themes',
	'Weather Software',
	'Widget Toolkit',
	'Gadgets & Widgets',
	'Operating System',
	'Application Development',
	'Compiler',
	'HTML Editor',
	'Integrated Development Environment (IDE)',
	'Interpreters & Compilers',
	'Programming Language',
	'Rapid Application Development',
	'Programming Languages - Utilities',
	'Web Development Software',
	'XML Tools',
	'Astrology Software',
	'Religious Software',
	'Antivirus',
	'Encryption Software',
	'Firewall Software',
	'Internet Security Software Suites',
	'Password Manager',
	'Privacy Software',
	'Spyware Remover',
	'Telecommunications',
	'Chat',
	'Data Transfer & Sync Software',
	'Dial-up Software',
	'E-mail Software',
	'FTP Software',
	'Instant Messaging Client',
	'Internet related',
	'Internet Relay Chat (IRC) Client',
	'Networking Software',
	'P2P & File-Sharing Software',
	'Remote Access',
	'SMS Tools',
	'VideoConferencing',
	'Web Phones & VoIP Software',
	'Wireless Networking Software',
	'ActiveX',
	'Chrome Extensions',
	'Firefox Add-ons & Plugins',
	'Internet Explorer Add-ons & Plugins',
	'Other Browser Add-ons & Plugins',
	'Web-based Aggregator',
	'Web Analytics',
	'Web Browsers',
	'Content Management System (CMS)',
	'Download Managers',
	'E-Business Suite',
	'Online Form Tools',
	'Online Service',
	'Online Storage & Data Backup',
	'Search Tools',
	'SEO Tools',
	'Web Site Tools',
	'Social Networking Software',
	'Audio',
	'Music Software',
	'Programming Languages - Compilers',
	'IDE Software',
	'Business Software',
	'Digital Audio Workstation',
	'Karaoke Software',
	'Digital Photo Tools',
	'Emulation',
	'File Archiver',
	'Network Tools',
	'Document Management Software',
	'Production & Recording Software',
	'Coding Utilities',
	'Application Packages',
	'File Manager',
	'System Utilities',
	'DVD Burners',
	'Email Client',
	'FTP Client',
	'CAD Software',
	'Internet Operations',
	'Digital Photograph',
	'IMS',
	'Office Suites',
	'Other Games',
	'Data Transfer',
	'Database Software',
	'Desktop Publishing Software',
	'3D Software',
	'Antivirus Software',
	'Mainframe Application Failure Resolution Solution',
	'Operating Systems & Updates',
	'Miscellaneous',
	'Program',
	'Presentation Program',
	'Spreadsheet Software',
	'Telecommunications - Other Utilities',
	'Text Editor',
	'Word Processing Software',
	);
$keys_terms = array();
foreach ($terms as $name) {
	$term_items = taxonomy_get_term_by_name($name, 'software_type');
	if(!empty($term_items)){
		$term = reset($term_items);
		$keys_terms[$term->tid] = $term->name;
	}
}

dpm($keys_terms);